---
- hosts: webservers
  tasks:
  - name: Show how variables can be registered
    shell: pwd
    register: pwd_output
  - name: What got saved
    debug: var=pwd_output
  - name: The return code
    debug: msg="Return code was {{ pwd_output['rc'] }}"
